Python/web/django/votes/mainapp/urls.py
from django.urls import path
from .views import *


app_name = 'mainapp'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', VoteDetailView.as_view(), name='detail'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', vote, name='vote'),
]

Python/web/django/votes/votes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))
]

Python/web/django/votes/mainapp/models.py
from django.db import models


class Question(models.Model):
    """
    Вопрос
    """
    text = models.CharField(max_length=255, verbose_name='Текст вопроса')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    def __str__(self):
        return '({}) Вопрос: {} был создан {}'.format(self.pk ,self.text, self.pub_date)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'
        

class Choise(models.Model):
    """
    Вариант ответа
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255, verbose_name='Текст варианта ответа')
    votes = models.IntegerField(default=0, verbose_name='Количесто лайков')

    def __str__(self):
        return 'Вопрос: {} - вариант ответа: {}'.format(self.question, self.text)

    class Meta:
        verbose_name = 'Вариант ответа'
        verbose_name_plural = 'Варианты ответа'

Python/web/django/votes/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.urls import reverse
from django.views.generic import ListView, DetailView


class IndexView(ListView):
    template_name = 'mainapp/index.html'
    context_object_name = 'questions'
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вопросы'
        return context

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class VoteDetailView(DetailView):
    model = Question
    template_name = 'mainapp/detail.html'


class ResultsView(DetailView):
    model = Question
    template_name = 'mainapp/result.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choise = question.choise_set.get(pk=request.POST['choise'])
    except:
        context = {
            'question': question,
            'error_message': 'Вы не выбрали вариант ответа!',            
        }
        return render(request, 'mainapp/detail.html', context)
    else:
        selected_choise.votes += 1
        selected_choise.save()
    return HttpResponseRedirect(reverse('mainapp:results', args=(question_id,)))

Python/web/django/votes/mainapp/templates/mainapp/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'mainapp/style.css' %}">

<h1>{{ question.text }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'mainapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choise in question.choise_set.all %}
    <input type="radio" name="choise" id="choise{{ forloop.counter0 }}" value="{{ choise.id }}">
    <label for="choise{{ forloop.counter0 }}">{{ choise.text }} (choise{{ forloop.counter0 }} | {{ choise.id }})</label>
    <br><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
<a href="{% url 'mainapp:index' %}">На главную</a>

Python/web/django/votes/mainapp/templates/mainapp/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'mainapp/style.css' %}">

<h1>{{ title }}</h1>

{% for question in questions %}
    <a href="{% url 'mainapp:detail' question.id %}">{{ question.text }} ({{ question.pub_date }})</a>
    <ul>
        {% for choise in question.choise_set.all %}

                <li>
                    {{ choise.text }} - {{ choise.votes }}
                </li>

        {% endfor %}
    </ul>
{% endfor %}

Python/web/django/votes/mainapp/templates/mainapp/result.html
{% load static %}
<link rel="stylesheet" href="{% static 'mainapp/style.css' %}">

<h1>{{ question.text }}</h1>
<ul>
{% for choise in question.choise_set.all %}
    <li>
        {{ choise.text }} - {{ choise.votes }} Голос{{ choise.votes|pluralize:'ов' }}
    </li>
{% endfor %}

</ul>
<a href="{% url 'mainapp:detail' question.id %}">Проголосовать ещё?</a>
<br><br>
<a href="{% url 'mainapp:index' %}">На главную</a>